name: Deploy React Application

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Verify build environment
        run: node verify-build-environment.js
        
      - name: Install dependencies
        run: npm install
        
      - name: Debug environment
        run: |
          echo "Repository structure:"
          ls -la
          echo "Node.js version:"
          node -v
          echo "NPM version:"
          npm -v
          
      - name: Build
        run: npm run build
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      # Create proper artifact structure for GitHub Pages
      - name: Fix artifact structure
        run: |
          # Ensure proper structure
          echo "Setting up correct artifact structure..."
          # Create a temporary directory with clean structure
          mkdir -p _site
          # Copy build contents to _site
          cp -r build/* _site/
          # List contents to verify
          echo "Artifact contents:"
          ls -la _site/
          
      # Use v2 of upload-pages-artifact which is compatible with v4 of deploy-pages
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '_site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
