name: Deploy React Application

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Verify build environment
        run: node verify-build-environment.js
        
      - name: Install dependencies
        run: npm install
        
      - name: Debug environment
        run: |
          echo "Repository structure:"
          ls -la
          echo "Node.js version:"
          node -v
          echo "NPM version:"
          npm -v
          echo "Current directory:"
          pwd
          
      - name: Build
        run: npm run build 2>&1 | tee build_output.log
        
      - name: Upload build logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build_output.log
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      # Direct artifact preparation
      - name: Package Pages Files
        run: |
          # Create artifact directory with proper structure
          mkdir -p pages-artifact
          # Copy build to artifact directory
          cp -r build/* pages-artifact/
          # Ensure artifact includes all required files
          ls -la pages-artifact/
        
      # Use latest artifact upload version
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: pages-artifact
          retention-days: 1
          if-no-files-found: error

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./pages-artifact
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
